version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: bkash@123123
      MYSQL_DATABASE: multibank
      MYSQL_USER: bkash-dev
      MYSQL_PASSWORD: bkash@123123
    volumes:
      - "./volumes/mysql:/var/lib/mysql:rw"
      - "./volumes/config/my.conf:/etc/mysql/conf.d/config-file.cnf"
